// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct PrismaMigration {
    pub id: String,
    pub checksum: String,
    pub finished_at: Option<NaiveDateTime>,
    pub migration_name: String,
    pub logs: Option<String>,
    pub rolled_back_at: Option<NaiveDateTime>,
    pub started_at: NaiveDateTime,
    pub applied_steps_count: u32,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: Option<String>,
    pub email: Option<String>,
    pub image: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub email_verified: bool,
}

