// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct SummitRegistrant {
    pub id: i32,
    pub user_id: i32,
    pub no_hp: String,
    pub universitas: String,
    pub jurusan: String,
    pub batch: i32,
    pub role: String,
    pub link_drive: String,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: Option<String>,
    pub email: String,
    pub password: String,
    pub email_verified: bool,
    pub image: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

